theme: jekyll-theme-minimal
title: Aitor Arrieta
layout: default
plugins:
    - jekyll-optional-front-matter
    - jekyll-redirect-from
include:
    -README.md
optional_front_matter:
  remove_originals: true
defaults:
  - scope:
      path: "*.md"
    values:
      layout: default
tagline: Lecturer and Researcher at Mondragon University
twitter:
    - username: aitorarrieta
social:
  links:
    - https://twitter.com/aitorarrieta
description: Aitor Arrieta is a lecturer and researcher at Mondragon University. His main researh interests are Cyber-Physical Systems testing, regression testing, search-based software testing and simulation-based testing.

bio: Aitor Arrieta is a lecturer and researcher at Mondragon University. He got his PhD in software engineering at Mondragon University in 2017. The PhD was awarded by 
    <a href="https://www.sistedes.es/" target=_blank>SISTEDES</a> 
    as the best PhD in software engieering preseted in 2017. In addition, he was awarded by <a href="https://www.scie.es" target=_blank>SCIE</a> and <a href="https://www.fbbva.es/" target=_blank>Fundación BBVA</a> as an early-stage researcher for his research in the field of software development and testing of industrial applications. He currently leads the
    <a href="https://adeptness.eu" target=_blank>ADEPTNESS</a> 
    H2020 project, which aims at researching on DevOps methods to be applicable and scalable in Cyber-Physical Systems</a>.<p>


    <i class="fa fa-envelope-o" aria-hidden="true"></i>
    <span class="sr-only">Mail:</span>&nbsp;&nbsp;<a href="mailto:aarrieta@mondragon.edu">aarrieta@mondragon.edu</a><br>
    <i class="fa fa-twitter" aria-hidden="true"></i>
    <span class="sr-only">Twitter:</span>&nbsp;&nbsp;<a href="https://www.twitter.com/aitorarrieta">@aitorarrieta</a>
logo: assets/AitorArrieta.jpg
logo_title: Aitor Arrieta
