theme: jekyll-theme-minimal
title: Jennifer J. Gago Muñoz
layout: default
plugins:
    - jekyll-optional-front-matter
    - jekyll-redirect-from
include:
    -README.md
optional_front_matter:
  remove_originals: true
defaults:
  - scope:
      path: "*.md"
    values:
      layout: default
tagline: Customer Success Engineer at MathWorks, Former Researcher at UC3M RoboticsLab
#twitter:
 #   - username: ...
#social:
 # links:
  #  - https://twitter.com/...
description: Jennifer J. Gago Muñoz is a robotics engineer working in the MathWorks academic group as a technical specialist. She is responsible for providing solutions to university professors and researchers to include computational thinking and Model-Based Design in their activities. Prior to joining MathWorks in 2019, she worked with portable radiography equipment as an industry researcher. She also worked in academia researching on the use of anthropomorphic manipulators and AI for automated sign language learning by humanoid robots. Jennifer holds a bachelor’s degree in industrial engineering with a specialization in electronics and automation and a master’s degree in robotics and automation from University Carlos III of Madrid. She is currently completing a distance learning degree in philosophy. </a><p> 

bio: Jennifer J. Gago Muñoz is a robotics engineer working in the MathWorks academic group as a technical specialist. She is responsible for providing solutions to university professors and researchers to include computational thinking and Model-Based Design in their activities. Prior to joining MathWorks in 2019, she worked with portable radiography equipment as an industry researcher. She also worked in academia researching on the use of anthropomorphic manipulators and AI for automated sign language learning by humanoid robots. Jennifer holds a bachelor’s degree in industrial engineering with a specialization in electronics and automation and a master’s degree in robotics and automation from University Carlos III of Madrid. She is currently completing a distance learning degree in philosophy. </a><p> 

    <i class="fa fa-envelope-o" aria-hidden="true"></i>
    <span class="sr-only">Mail:</span>&nbsp;&nbsp;<a href="mailto:jennifer.gmunoz@gmail.com">jennifer.gmunoz@gmail.com</a><br>
    <i class="fa fa-file" aria-hidden="true"></i>
    <span class="sr-only">CV:</span>&nbsp;&nbsp;<a href="/assets/Jenn_CV.pdf">Download CV (PDF)</a><br>
    <i class="fa fa-youtube-play" aria-hidden="true"></i>
    <span class="sr-only">YouTube:</span>&nbsp;&nbsp;<a href="https://www.youtube.com/channel/UCP1WOIhEx3kAY7nWfwCCOVw/videos">YT Channel</a><br>
    <i class="fa fa-linkedin-square" aria-hidden="true"></i>
    <span class="sr-only">LinkedIn:</span>&nbsp;&nbsp;<a href="https://www.linkedin.com/in/jennifer-gago/">LinkedIn Profile</a><br>
    <i class="fa fa-github" aria-hidden="true"></i>
    <span class="sr-only">GitHub:</span>&nbsp;&nbsp;<a href="https://github.com/jgagom">GitHub</a>
logo: assets/myfoto.jpg
logo_title: Jennifer Gago
